### ISSUE TITLE
Time unit pluralization

### ISSUE THREAD

**Issue by sanderaido** [siddii/angular-timer#131]
Problem is with other languages beside English. Pluralization should accept a string to append to the existing string or better yet accept a full plural form of the unit (because maybe there are languages that don't use just a suffix for pluralization but a whole other word).

Right now if I have a different suffix for a plural form in my language, I can't use it because the only option is to add a 's' to the end.
Current: {{minutes}} minute{{minutesS}}
Suggestion: {{minutes}} {{minuteUnit('minute','minutes')}}                

Also I don't understand why 0-units are also singular? Correct would be '0 hours 0 minutes 1 second' not '0 hour 0 minute 1 second'  
EDIT: I see zero-units were made singular in a recent fix (ver 1.1.8) but this is wrong and should be changed back. Zero is always plural! (0 books, 0 cars, 0 hours).

**Comment by polomarcus** [comment]
Done by https://github.com/siddii/angular-timer/pull/154
