### ISSUE TITLE
Multiple Countdowns

### ISSUE THREAD

**Issue by arun0009** [siddii/angular-timer#166]
I have to show multiple countdowns on page and I refresh the countdowns in controller every 30 seconds. However all countdowns are getting reset to same seconds if I use $scope.$broadcast('timer-set-countdown'. Is there a way to broadcast to multiple countdowns in loop?

**Comment by siddii** [comment]
Hey @arun0009 - Not by default through this module, because of the way Angular's scope `broadcast` method works. However, you could create a new scope wrapping the countdown/directive's scope & manage them by yourself if needed.

**Comment by polomarcus** [comment]
Hi @arun0009,

I use this for example :
```javascript
        document.getElementById('chrono').getElementsByTagName('timer')[0].start();
        document.getElementById('chrono').getElementsByTagName('timer')[0].stop();
```
Of course, it would be better to use the angular way like @siddii said.

**Comment by arun0009** [comment]
Thanks! @siddii and @polomarcus. I got the countdown to take scope value and updating it now reflects new countdown value.
