### ISSUE TITLE
Timer end-time value can not be set from controller

### ISSUE THREAD

**Issue by dipansaha** [siddii/angular-timer#167]
Hi,
this issue was happened before and you have provided this pluker http://plnkr.co/edit/zjrU6j?p=preview which was seems solve but  this issue comes back again. plunker code also doesn't work. can you please suggest any work around?

Thanks
Dipan

**Comment by siddii** [comment]
Sorry, been busy with other things. I'll take a look tonight.

**Comment by dipansaha** [comment]
Thanks in advance :)

**Comment by siddii** [comment]
It just needed some external scripts. This plunkr works fine now - http://plnkr.co/edit/PK3zqn?p=preview

I have created an issue to handle graceful fallback - #168

**Comment by dipansaha** [comment]
Hi siddii,thanks. It works.

Cheers,
Dipan Saha
0412 046 873









Date: Fri, 13 Mar 2015 16:10:16 -0700

**Comment by IcebergRage** [comment]
It still does not work

**Comment by josx** [comment]
still not working, anyone knows why?
