### ISSUE TITLE
Plural / Singular units

### ISSUE THREAD

**Issue by thenovacreator** [siddii/angular-timer#173]
I really do not get how your Plural / Singular units System is working. I want for singular "Minute" and for plural "Minuten" and tried:

Minute{{MinutenS}}
Minuten{{MinuteS}}
Minute{{MinuteN}}

but none of them seems to work. What could i do to get this working? The syntax is very confusing.

Maybe it would be easier if you would use a syntax like so [minute|minutes]. This would ne inspired by http://laravel.com/docs/5.0/localization#pluralization

**Comment by polomarcus** [comment]
Hi @thenovacreator ,

Please see : http://siddii.github.io/angular-timer/index.html#/clock-timer-i18n 

Don't hesitate to comment if you have feedback

**Comment by thenovacreator** [comment]
I have tried this but it does not help in my situation.
Am 12.04.2015 22:26 schrieb "Paul Leclercq" <notifications@github.com>:
