### ISSUE TITLE
Defining End Time with angular

### ISSUE THREAD

**Issue by thenovacreator** [siddii/angular-timer#174]
How do i set the value of the endtime dynamically?

Something like this does not work:

<timer end-time="{{object.endTime}}">{{days}} days, {{hours}} hours, {{minutes}} minutes, {{seconds}} seconds.</timer>

**Comment by siddii** [comment]
The end time needs to be in millions. The format you are seeing is the rendering/display time.

**Comment by thenovacreator** [comment]
My fault i meant something like this


<timer end-time="{{object.time}}">{{days}} days, {{hours}} hours, {{minutes}} minutes, {{seconds}} seconds.</timer>
