### ISSUE TITLE
Reset single countdown timer

### ISSUE THREAD

**Issue by xyNNN** [siddii/angular-timer#176]
I have a countdown timer which is defined with a countdown of 300 seconds. After clicking on a button i want to reset the timer to the predefined 300 seconds and start the counter again. 

Any solutions?

Thanks in advance!

**Comment by AaronBuxbaum** [comment]
Something like this should do it:

```
ctrl.reset = function () {
   $scope.$broadcast( 'timer-set-countdown', 300 );
   $scope.$broadcast('timer-start');
};
```

**Comment by xyNNN** [comment]
@AaronBuxbaum Thanks for your reply. I will give it a try and will give you feedback. I didn't know the timer-set-countdown event :)

**Comment by xyNNN** [comment]
@AaronBuxbaum It worked like expected. Thanks for your hint!
