### ISSUE TITLE
Change "countdown" attribute from AngularJS controller?

### ISSUE THREAD

**Issue by jasonshah** [siddii/angular-timer#21]
Hi,
Is there a way to change the "countdown" attribute from the AngularJS controller?

I tried something like this:

index.html

```
<timer interval="1000" countdown="{{timerTime}}">{{seconds}}</timer>
```

controller.js

```
controller('WorkoutCtrl', ['$scope', function($scope) {
    $scope.timerTime = 15;
    ...
}]);
```

but I receive an error:
"Error: Syntax Error: Token 'timerTime' is unexpected, expecting [:] at column 3 of the expression [{{timerTime}}] starting at [timerTime}}]."

Thanks for the great Directive!

**Comment by mattkrebs** [comment]
My timer markup looks like this
```html
<timer autostart='false' interval="1000" countdown="countdown">{{mminutes}}:{{sseconds}}</timer>
```

The above solution is working to update {{countdown}} but it doesnt update {{mminutes}} or {{sseconds}}

Any thoughts on this?

Thanks for creating this directive!

**Comment by rahmanict** [comment]
is it your js or github?
<script src="http://siddii.github.io/angular-timer/app/js/timer.js"></script>

**Comment by samoeba** [comment]
@zeeshanjan82 @siddii has this line of code gone away?  ```$scope.$broadcast('timer-set-countdown', 60); ``` I ran into the code below in the source code and I'm wondering what it does. How is it invoked? 
``` 
$scope.$on('timer-set-countdown', function (e, countdown) {
    $scope.countdown = countdown;
});
```

**Comment by OlympicLarry** [comment]
var value = 1800;
$scope.$broadcast('timer-set-countdown-seconds', value);

**Comment by meShakti** [comment]
I am having the same issues as @mattkrebs

**Comment by HeenaOberoi** [comment]
I have a timer as below which works fine for Chrome and Firefox,but skips a second many times in IE.

<timer autostart="false" interval="1000" countdown="OverAllTimeRemaining" finish-callback="TimeOutFn()">{{mminutes}}:{{sseconds}}</timer>

In controller,
$rootScope.OverAllTimeRemaining = 4000;//Added arbitary value which ideally is dynamic-This time is in seconds

The timer is running fine yet skips seconds only in IE.

Any solution???
