### ISSUE TITLE
How to change start time after initialize

### ISSUE THREAD

**Issue by andrewvmail** [siddii/angular-timer#225]
is it possible to change start-time again after the page have already initialize ? im trying to do it by using a scope variable in the starttime but it doesnt work. i had to refresh the page to get the start time to appear properly again.

**Comment by slartibarfast** [comment]
I'm doing this by:

			$scope.$broadcast('timer-reset');
			$scope.$broadcast('timer-add-cd-seconds', ms );
			$scope.$broadcast('timer-start');

**Comment by xfg** [comment]
slartibarfast, Thanks man!

**Comment by Cornally** [comment]
I've done it this way: `$scope.$broadcast('timer-set-countdown-seconds', countdownSeconds);`

**Comment by AhSem** [comment]
$scope.$broadcast('timer-set-countdown-seconds', yourCountdownSeconds);  

This helps to set the update the countdown time. But when I start it using 

$scope.$broadcast('timer-start');

the timer count down value becomes NaN.

Any idea why is that so?
