### ISSUE TITLE
Dynamically binding countdown value

### ISSUE THREAD

**Issue by wisemanIV** [siddii/angular-timer#23]
Great work. How do I dynamically bind the countdown value from data retrieved from a remote REST service and start the countdown once the data is retrieved?

**Comment by beinguideveloper** [comment]
how do i bind start-time as below is my code

My HTML Code:
<div id="timer" class="container-fluid pad0 {{disTimer}}" ng-if="page !='init'">
                           <div class="timerBlock">
                                  <strong><timer autostart="false" start-time="{{startTimerVal}}">{{minutes}}:{{seconds}}</timer></strong>&nbsp;&nbsp;mins
                                  over
                           </div>
                     </div>
 
My JS Code :
 
 
$scope.startTimerVal = ($scope.startHour*360000)+($scope.startMin*60000)+($scope.startSec*1000);
 
In startTimerVal I get dynamic value where I convert that value into miliseconds
 
Using this I get below error
 
Error: [$parse:syntax] Syntax Error: Token '{' invalid key at column 2 of the expression [{{startTimerVal}}] starting at [{startTimerVal}}].

**Comment by beinguideveloper** [comment]
My HTML Code:

[timerautostart="false"start-time="{{startTimerVal}}"]{{minutes}}:{{seconds}}[/timer]

i am using square brackets instead of greater than and less than sign to show my demo code as those sign wont works here
