### ISSUE TITLE
How to prevent to be reset timer on page refresh

### ISSUE THREAD

**Issue by ravi-ku** [siddii/angular-timer#239]
Hi 
I have a scenario, where if timer is started then it should not be reset on page refresh. it should be continue whether page is refreshed or not.

Thanks!
mcamail2002@gmail.com

**Comment by siddii** [comment]
@ravi-ku - I don't think its doable. When the page refreshes, the entire angular DI will get bootstrap. The only you can do is by persisting your state on the server side (or Browser's localHistory) & resume the directive's state after the page gets refreshed.

Hope that helps

**Comment by ravi-ku** [comment]
I want to utilize this plugin in Online Test. Where timer should not be reset if page refresh. It should maintain the state of the timer. Please help, how to achieve this.

Thanks!
