### ISSUE TITLE
new tag version 1.3.4

### ISSUE THREAD

**Issue by rickerd** [siddii/angular-timer#254]
Please update master to a new tag.
The bower file changed from momentjs to moment.
And now bower is fetching 2 times momentjs. Please update it.

**Comment by Splaktar** [comment]
For now I'm just doing the following:
```
    "angular-timer": "ea3d7e8fdfb81a2aa66875f96376eb82e1e38017",
```

**Comment by rickerd** [comment]
Thats a "hack" not a solution

**Comment by Splaktar** [comment]
@siddii Thank you!

**Comment by Splaktar** [comment]
@rickerd your comment came through very negatively and felt like a lack of respect for someone using their very limited spare time to offer a workaround. I do understand the difference between tags and hashes.

**Comment by rickerd** [comment]
Come on, thats really bullshit.
Im asking for a new tag not for a 1000 dollar loan.

And text hasnt got emotion so i think you read it wrong.
I dont like hacks and stuff to accomplish things im a professional not a scriptkiddy.

Thanks @siddii for the new tag
