### ISSUE TITLE
finish-callback()  problem

### ISSUE THREAD

**Issue by zygmcc** [siddii/angular-timer#272]
my codes:
```
<div ng-show="smsSent">
<timer interval="1000" countdown="60" end-time="0" finish-callback="smsSent=!smsSent">{{seconds}}</timer>
</div>

```
i suppose to countdown the time for 1 min. but when 1 min passed,timer calls the finish-callback(), and smsSent changs it's value,.but my view do not change. I mean, atter that,the <div> block do not hiden

**Comment by maxfriedmann** [comment]
Can you use countdown and end-time together? I thought countdown is an absolute value, like 3400s. end-time is a relative date (in the future) the timer wants to count towards.

**Comment by zygmcc** [comment]
tks @maxfriedmann , I have solved this problem. There is not question between 'countdown ' and 'end-time', but the var 'smsSent'.   
I will close this issue :)
