### ISSUE TITLE
Countdown timer not working.

### ISSUE THREAD

**Issue by anil1712** [siddii/angular-timer#28]
Hi I was trying to use this directive as a countdown timer but its not working. I am using below code.

<timer start-time="1357020000000">{{days}} days, {{hours}} hours, {{minutes}} minutes, {{seconds}} seconds.</timer>

Here Following is the timer clock setting for the days, hours, minutes & seconds elapsed since January 1, 2013 (GMT-6)

(01 Jan 2013 06:00:00 GMT = 1357020000000 milliseconds)

I want a countdown timer for 3 hours, so I added 180 ms into the current time stamp
eg: 
var ct = new Date().getTime() + 180_60_1000;
ct = 1384205227175;

Now our code will be

<timer start-time="1384205227175">{{days}} days, {{hours}} hours, {{minutes}} minutes, {{seconds}} seconds.</timer>        

and the output is something like this
 -3 hours, -59 minutes, -27 seconds.

Please give me some solution for this,

**Comment by heshamelmasry77** [comment]
This shit is not working anymore 🍶
