### ISSUE TITLE
Breaking change released as patch version

### ISSUE THREAD

**Issue by greglockwood** [siddii/angular-timer#309]
I don't know whether adherence to semantic versioning (semver) is a goal of this project or not, but the latest release, 1.3.5, has certainly not complied with semver semantics.

According to semver, the new 1.3.5 version should have been a patch release. This means that only bug fixes should be included. Were new features to be added, that would be 1.4.0. And were breaking changes to be included, as they indeed were due to the removal of the methods added to the DOM element (in PR  #297), it would be version 2.0.0.

## Why is semver important?

The biggest reason I think it is important is because both bower and npm by default assume that any dependency follows semver. The reason I say they do this is because when you install a dependency, they add it to your `bower.json` or `package.json` as `"~n.n.n"` (where `n` corresponds to an integer), which is the same as `"n.n.x"`. In other words, by default, newer patch versions are permitted to be installed, because they are assumed to not contain any breaking changes.

By breaking this assumption, you cause problems for users of your library who wake up one day to find that simply by running `bower install`, exceptions are caused due to removal of methods that we were relying on.

## Critical functionality has been removed

The removal of those methods added to the DOM element has made it much more difficult, if not impossible, to target and control a specific timer from a completely different part of the application code.

It may not have been idiomatic AngularJS code, but we were relying on code like this to work:

    angular.element('#some-id-selector')[0].resume();

There is no easy equivalent now that I can see, to target and control a specific timer. The scope events don't allow a parameter to specify which timer to affect, so I can't use `$rootScope.$broadcast('timer-start', { id: 'some-id' })` or similar.

So whilst I am all for fixing the IE compatibility, it should be in a new version 2.0.0, and I believe that comparable functionality to enable targeting specific timers should be added.

**Comment by siddii** [comment]
Hi @greglockwood ,

Your concerns are well noted! Hopefully, this won't happen again.

Sorry for the trouble.

**Comment by greglockwood** [comment]
What are you putting in place to make sure it doesn't? Do you plan on adopting semver?

My suggestion is to release another patch version reverting the breaking change, and re-releasing the breaking change as 2.0.0 for those that want the IE support.

Alternatively, is there any way for me to now target specific timers easily from anywhere in the application?
