### ISSUE TITLE
Set timer from model

### ISSUE THREAD

**Issue by robertochingon** [siddii/angular-timer#34]
Hi, 

  I see the other two issues are related with same topic. I read them, but it´s not clear to me. 

I need to set the end-time attribute dinamically from a model (coming from REST API). I don´t want to go to a controller, because I need to apply it to every element in an array (inside a ng-repeat).

 <timer end-time={{time}}>{{hours}}:{{minutes}}:{{seconds}}</timer></td>

Is it possible to do it?

Thanks,
Roberto.

**Comment by shivenigma** [comment]
I can't do this, I am getting unknown provider $elementProvider error when trying to inject $element in my controller.
