### ISSUE TITLE
$scope.$broadcast("timer-add-time") error

### ISSUE THREAD

**Issue by gregglind** [siddii/angular-timer#40]
I get these errors:

```
$scope.addSeconds is undefined
```

Changing it to `$scope.addCDSeconds` gives

`$apply already in progress`

This the right way to add seconds to a countdown?

**Comment by mtabesa** [comment]
I have multiple timer displayed. How can I add second to one timer only, because using
 $scope.$broadcast ('timer-add-cd-seconds', 1800), sure did add 30 minutes  but it added 30 minutes to all my timer.
