### ISSUE TITLE
Dynamically bind end-time (e.g. allow to pass variables via a controller)

### ISSUE THREAD

**Issue by azachar** [siddii/angular-timer#53]
Hello!
Thank you for your great work! I really like it! 

I am using it as a count down timer to show that the event registration can start.

To follow the MVC pattern I am setting up some "dates" in the page controller and do some logic related to it, but unfortunately I am unable to pass my `$scope.end-time` variable to your directive `<time end-time="{{end-time}}"` ...

Do you have any suggestions how to achieve it? 

Thank you very much!

Best regards,
Andrej

**Comment by sanketwankhade01** [comment]
I have same problem with it. can you suggest me simple solution to it..

**Comment by idf** [comment]
@sanketwankhade01 You can try `ng-if`. After you load the time using Ajax, set ng-if condition to true, the timer will run after the promise resolve in `ng-if`.
