### ISSUE TITLE
Multiple timers with id

### ISSUE THREAD

**Issue by willyyr** [siddii/angular-timer#57]
I have multiple timers on a page where each timer needs to be stopped and started at different events. Looking at examples/angularjs-multiple-timers.html i cannot find any hints on how to stop only a specific timer. Is it possible to pass an id to a timer to do that?

**Comment by shubhamkumarnayak** [comment]
I need the exact thing....

**Comment by bayucandra** [comment]
I have tried the latest version looks it is not working with `$('timer')[0].start()`.

It said: "Uncaught TypeError: $(...)[0].start is not a function".

I am using it inside "Angular ui router" is it the one which caused the problem?

Any help is appreciated. Thanks.
