### ISSUE TITLE
multiple timers in a repeat?

### ISSUE THREAD

**Issue by RogueSheep-nl** [siddii/angular-timer#58]
Hi Sidii,
great work on this lib.

I am trying to get multiple timers running using the timestamp from an array:

```
<div ng-repeat="category in categories">
   {{category.name}}
  <timer end-time="category.ts">{{days}}, {{hours}}, {{minutes}}, {{seconds}}.</timer>
</div>
```

This does not get the countdown running.
I'm kinda new to Angular so maybe I am missing some vital knowledge.
(I am trying to get this working using only Angular, without jQuery.)
Could you point me in the right direction on how to get this working?

Thanks!

**Comment by mollycr** [comment]
That was my problem! Thank you so much, it would have taken me so long to figure that out :D

**Comment by mkarrfan** [comment]
```
<div ng-repeat="category in categories">
   {{category.name}}
  <timer end-time="category.ts">{{days}}, {{hours}}, {{minutes}}, {{seconds}}.</timer>
</div>
```

Is this working?
