### ISSUE TITLE
Multiple Timers Stop Events

### ISSUE THREAD

**Issue by patnevin** [siddii/angular-timer#73]
Loving the timer so far - really simple to use. I'm having one small issue however.

I have multiple timers all being kicked off with different countdown values (essentially a list of ebay style auction items counting down) inside an ng-repeat.

I see there is a 'timer-stopped' event which is ideal as I'd like to refresh the item on this event, however I can't seem to find a way for the event to tell me which timer has expired.

Is there a way of doing this? Neither the "data" or "event" arguments seem to have a timerId or equivalent, and I can't see this being used in any of your examples.

Thanks in advance.

**Comment by mkarrfan** [comment]
The plnkr is not working!
