### ISSUE TITLE
Cannot use a scope-variable on "end-time" 

### ISSUE THREAD

**Issue by tmundt** [siddii/angular-timer#95]
I try to set a timer in milliseconds on a "end-time" attribut like

```
  $scope.endTime = 343434334; // some value
```

and in HTML:

```
<timer end-time="endTime" max-time-unit="'hour'"> .... </timer>
```

There is no countdown at all, it starts counting from the first second from the start.

Do I oversee something or is it not possible to set a value for end-time?

**Comment by juaniiton1** [comment]
@kodypeterson any solution for this?

**Comment by judsonmusic** [comment]
I also am having this issue. Any ideas? Endtime is not getting populated in time.
