### ISSUE TITLE
Passing asynchrous loaded data do timer

### ISSUE THREAD

**Issue by mjarmoc** [siddii/angular-timer#99]
Hello,

Got a big problem with passing data asynchrously to timer. I am using my service Api to obtain data from JSON by $http.get(). After success I am ascribing them to $scope:

```
angular.module('App')  .controller('MainCtrl', function ($scope, Api) {
  Api.events().success(function(data){
      $scope.countdown = 1406887200000;       
  });  
});
```

and binds it in my html:
  `<timer ng-attr-end-time="countdown"></timer>`

Data are passed but timer is initialising without data. How could i refresh it? $scope for the element looks like it: 

interval: null
startTimeAttr: null
endTimeAttr: 1406887200000
countdownattr: null
finishCallback: null
autoStart: null
maxTimeUnit: null
startTime:  {  } 
endTime: null
timeoutId: null
countdown: null
isRunning: false
start: null
resume: null
pause: null
stop: null
clear: null
millis: 0
seconds: 0
minutes: 0
hours: 0
days: 0
months: 0
years: 0
secondsS: s
minutesS: s
hoursS: s
daysS: s
monthsS: s
yearsS: s
sseconds: 00
mminutes: 00
hhours: 00
ddays: 00
mmonths: 00
yyears: 00
stoppedTime:  {  }

**Comment by sfielder** [comment]
@mjarmoc do you have a code sample of how you solved this? struggling with the same and not following your resolution

thank you!
